authors:
  gayithriponnapalli:
    name: Gayithri Ponnapalli
    description: AI Engineer | Python · FastAPI · RAG · LLMs
    avatar: ../assets/PHOTO-Gayithri-Pojoai copy.jpg
    url: https://www.linkedin.com/in/YOUR_LINKEDIN_USERNAME
